//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gizem_köklü.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class about
    {
        public int id { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string website { get; set; }
        public string phone { get; set; }
        public string city { get; set; }
        public string age { get; set; }
        public string degree { get; set; }
        public string email { get; set; }
        public string workflow { get; set; }
        public Nullable<int> experience { get; set; }
    }
}
