//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gizem_köklü.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CvDbEntities1 : DbContext
    {
        public CvDbEntities1()
            : base("name=CvDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<about> about { get; set; }
        public virtual DbSet<projects> projects { get; set; }
        public virtual DbSet<sertifikalar> sertifikalar { get; set; }
        public virtual DbSet<yetenekler> yetenekler { get; set; }
        public virtual DbSet<ilgiler> ilgiler { get; set; }
    }
}
